### ISSUE TITLE
can set delemiter and silent client disconnected?

### ISSUE THREAD

**Issue by mzelecom** [ReferenceType/StandardNetworkLibrary#23]
Hello,
1- Can the server be configured to trigger an event when it detects the end of a packet with \n\r (set delemiter)?
2- Is there a capability to configure the removal of clients who haven't sent any messages for approximately 10 minutes(silent client)?

**Comment by ReferenceType** [comment]
Hi
1 -  ByteMessageTcpServer  and ByteMessageTcpClient sends messages with 4 byte length header internally. This means messages trigger event only when they are fully constructed on receiving end. So if you send 32 byes or 2 gigabytes you will receive that  as a single message without fragmentation.

What you ask is custom protocol. If you have strings that needs to be delimited by \n\r , split them on sender side and send them line by line as a single message(1 line is 1 message) or send all fully and parse them on receiving end and invoke your own events(more efficient).

2- This is also a custom feature, and application dependent. You can implement this yourself very easily on your application.
I give you a quick example:

Make a dictionary and set the value true when client is connected and every time you receive a message from client.
Guid is the session id/client id.
```c#
ConcurrentDictionary<Guid,bool> messageTracker = new ConcurrentDictionary<Guid, bool>();
```
Create some maintainer task to check  and reset this dictionary
```c#
 Task.Run(async () =>
            {
                while (true)
                {
                    await Task.Delay(1_000_000);
                    foreach (var entry in messageTracker)
                    {
                        if (entry.Value == false)
                        {
                            // Drop Client.
                        }
                        else
                        {
                            messageTracker[entry.Key] = false;
                        }
                    }
                }
            });
```

If you have further questions ask me, and please give more information about what you are trying to do so i can understand the context better.

**Comment by mzelecom** [comment]
Thanks for your guidance.
I have a game server, of course, the game is for 2 players, like Manch.
About 2000 clients are online and I use mysql database, of course, I wrote sync reading and writing and I don't use async.
Do I need to use threadpool or task with StandardNetworkLibrary? Or do I not need to use it?

**Comment by ReferenceType** [comment]
I think you can handle 2000 clients.
This library is fully parallel and thread safe. I am internally using Net Threadpool. Everything scales up depending on your CPU core count.
I tried to keep interface very simple and keep the complexity hidden.

I didn't fully understand "Do I need to use threadpool or task with StandardNetworkLibrary? Or do I not need to use it?"
Can you please elaborate that?

**Comment by mzelecom** [comment]
when ServerBytesReceived raised. i send data to thredpool.is it ok?or i must remove it.
this is my code.
`
 Private Sub ServerBytesReceived(guid As Guid, bytes() As Byte, offset As Integer, count As Integer)
        Dim msg As String = Encoding.UTF8.GetString(bytes, offset, count)
        Try
            If msg.Contains(vbCrLf) Then
                Dim rmg As New Recive_msgss With {
                    .tc = guid,
                    .msg = msg
                }
                SmartThreadPool4.QueueWorkItem((AddressOf Recive_string), rmg)
	     end if
        Catch ex As Exception
        End Try
    End Sub
`

**Comment by ReferenceType** [comment]
I understand, its very good question.  There is a tricky point here.

All callbacks of server and client is called by a thread pool thread (same pool you are using) And .Net by default creates thread pool same size as your logical processor count (i.e, 16 core => 16 threads ) if all threads are saturated it creates 1 thread per 0.5 seconds. Practically this creation is very slow, telling from experience.

So if your event handler does some blocking work you will saturate the pool with 2000 clients quickly. Fortunately, there is a method ThreadPool.SetMinThreads(int,int) which you can set high number of threads to avoid this. (I dont know the equivalent in VBA)
Alternatively you can make your own pool ofc..

Now in the case that you want to use the bytes directly on separate thread or store them. You must do a copy. In your case You dont need to do it because you already call ``` Encoding.UTF8.GetString(bytes, offset, count)``` which does a copy.

So The answer is you don't need to use threadpool yourself.

**Comment by mzelecom** [comment]
I tested it, I don't know why, but when there are about 2000 people on the server, after a while, maybe 30 minutes, the server doesn't respond at once and the threadpool is full. That means the threads that are in the queue reach about 100,000 and are constantly added.
It is impossible to determine where exactly the problem is.
If you have a telegram and it is possible, I can send more information and get guidance from you.

**Comment by ReferenceType** [comment]
I have checked on my end to see if anything wrong in new version, but i have found no issues. Besides i'm actively using the library at work, stably.

it seems to me there 2 possibilities, either you are generating more request than your server can handle, probably this is due to your DB speed or computer specs. Or a bug, where your event handlers of messages are blocked permanently.
Unfortunately, I cant share my private information. Best of luck.
